# Generated by Django 5.1 on 2024-08-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='Imagens_salvas/'),
        ),
    ]
